Updated filtering of quotes from data in order to prevent failed items for kanboard. Counting succesfull and failed items. Changed returning data to main loop.

diff --git a/rssmail b/rssmail
--- a/rssmail
+++ b/rssmail
@@ -19,6 +19,7 @@ processfeed() {
    tmpfile=$( tempfile )
 
    new=0
+   err=0
    maxtime=$lasttime
    WGETFLAGS="$WGETFLAGS -q --timeout=10"
    wget $WGETFLAGS -O "$tmpfile" "$url" || { >&2 echo "Error retrieving $url."; rm -f "$tmpfile"; return 1; }
@@ -31,12 +32,13 @@ processfeed() {
       test $? -ne 0 && { >&2 echo "Error parsing feed from $url."; rm -f "$tmpfile" "$tmpfile.parsed"; return 1; }
    fi
    rm -f "$tmpfile"
+   error=0
    while read -r line
    do
       fn=${line/:*/}
       data=${line/????:/}
       case "$fn" in
-         "date") time=$(date -d "$data" "+%s") || { >&2 echo "Feed: $fn, error converting date format. ($line)"; }
+         "date") time=$(date -d "$data" "+%s" 2> /dev/null) || { >&2 echo "Feed ($name): Error converting date format. ($data)"; error=1; }
          ;;
          "titl") title="$data"
          ;;
@@ -46,22 +48,28 @@ processfeed() {
             desc="$data"
             if test "$lasttime" -lt "$time"
             then
-               new=$(($new + 1))
-               if test $domail -eq 1; then
-                  echo -e "<html><body><b>$title</b><p>${desc//^/\\n}<p><a href=$link>$link</a><p><i>Update: $(date -d @"$time" "+%Y/%m/%d %H:%M:%S")</i></body></html>" | mail -a 'Content-Type: text/html; charset="ISO-8859-1"' -r "$mailfrom" -s "$name: $title" "$mailto"
-               fi
-               if test $dokanboard -eq 1; then
-                  res=$(echo '{ "jsonrpc": "2.0", "method": "createTask", "id": 2134420212, "params": { "title": "'$name: $title'", "project_id": '$kbprid', "description": "#Description\n\n'$desc'\n\n#Link\n\n'$link'" } }' | kanboard | jq -r '.error')
-                  test "$res" = "null" || { >&2 echo "Feed: ($fn) Error adding task to kanboard ($res)."; }
+               if test $error -ne 0
+               then
+                  err=$(( $err + 1 ))
+               else
+                  if test $domail -eq 1; then
+                     { >&2 echo -e "<html><body><b>$title</b><p>${desc//^/\\n}<p><a href=$link>$link</a><p><i>Update: $(date -d @"$time" "+%Y/%m/%d %H:%M:%S")</i></body></html>" | mail -a 'Content-Type: text/html; charset="ISO-8859-1"' -r "$mailfrom" -s "$name: $title" "$mailto"; }
+                     new=$(($new + 1))
+                  fi
+                  if test $dokanboard -eq 1; then
+                     res=$(echo '{ "jsonrpc": "2.0", "method": "createTask", "id": 2134420212, "params": { "title": "'$name: $title'", "project_id": '$kbprid', "description": "#Description\n\n'$desc'\n\n#Link\n\n'$link'" } }' | kanboard | jq -r '.error')
+                     test "$res" != "null" && { >&2 echo "Feed ($name): Error adding task to kanboard (error: $res)."; err=$(($err + 1));}
+                     test "$res" = "null" && new=$(($new + 1))
+                  fi
                fi
                test "$time" -gt "$maxtime" && maxtime=$time
             fi
+            error=0
          ;;
       esac
-   done < "$tmpfile.parsed"
+   done < <(cat $tmpfile.parsed | tr -d \'\" )
    rm -f "$tmpfile.parsed"
-   echo "$maxtime"
-   return $new
+   echo $maxtime $new $err
 }
 
 readconfig() {
@@ -228,17 +236,16 @@ main() {
       test "$kbprid" = "null" && { echo "Kanboard project $kanboardproject not found."; exit 1; }
    fi
 
-   items=0
+   itemsok=0
+   itemserr=0
    for name in "${!time[@]}"
    do
-      result=$( processfeed "$name" "${time[$name]}" "${url[$name]}" )
-      items=$(( $items + $? ))
-      if test $? -eq 0
-      then
-         newtime[$name]=$result
-      fi
+      read maxtime new err < <(processfeed "$name" "${time[$name]}" "${url[$name]}" )
+      itemsok=$(( $itemsok + $new ))
+      itemserr=$(( $itemserr + $err ))
+      newtime[$name]=$maxtime
    done
-   test $items -gt 0 -a $dokanmail -eq 1 && { echo -e "There are $items itmes added to kanboard $kanboardproject." | mail -r "$mailfrom" -s "rssmail: $items items added to kanboard" "$mailto"; }
+   test $(( $itemsok + $itemserr )) -gt 0 -a $dokanmail -eq 1 && { ( test $itemsok -gt 0 && echo -e "There are $itemsok items added to kanboard $kanboardproject."; test $itemserr -gt 0 && echo -e "There are $itemserr items that failed to parse." ) | mail -r "$mailfrom" -s "rssmail: $itemsok items added to kanboard" "$mailto"; }
 
    rewriteconfig
 }
