Fixed big bug processing each feed twice!

diff --git a/rssmail b/rssmail
--- a/rssmail
+++ b/rssmail
@@ -14,14 +14,14 @@ processfeed() {
    tmpfile=$( tempfile )
    maxtime=$lasttime
    wget -q -4 --timeout=10 -O $tmpfile "$url" || { >&2 echo "Error retrieving $url."; rm -f $tmpfile; return 1; }
-   #xmlstarlet sel -t -m "//item" -o "titl:" -v "title" --nl -o "link:" -v "link" --nl -o "date:" -v "pubDate" --nl -o "desc:" -v "description" --nl < $tmpfile > $tmpfile.parsed 2> /dev/null || { >&2 echo "Error parsing feed from $url."; rm -f $tmpfile $tmpfile.parsed; return 1; }
    # First try standard parse
    $XML sel -t -m "//item" --var linebreak -n --break -o "titl:" -v "title" -n -o "link:" -v "link" -n -o "date:" -v "pubDate" -n -o "desc:" -v "translate(description, \$linebreak, '^')" -n $tmpfile 2> /dev/null > $tmpfile.parsed
+   # Next try parse with different XML name spaces
    if test $? -ne 0
    then
       $XML sel -N purl="http://purl.org/rss/1.0/" -N dc="http://purl.org/dc/elements/1.1/" -t -m "//rdf:RDF/purl:item" --var linebreak -n --break -o "titl:" -v purl:title -n -o "link:" -v purl:link -n -o "date:" -v dc:date -n -o "desc:" -v "translate(purl:description, \$linebreak, '^')" -n $tmpfile 2> /dev/null > $tmpfile.parsed
+      test $? -ne 0 && { >&2 echo "Error parsing feed from $url."; rm -f $tmpfile $tmpfile.parsed; return 1; }
    fi
-   test $? -ne 0 && { >&2 echo "Error parsing feed from $url."; rm -f $tmpfile $tmpfile.parsed; return 1; }
    rm -f $tmpfile
    while read line
    do
@@ -182,7 +182,7 @@ main() {
       result=$( processfeed "$name" "${time[$name]}" "${url[$name]}" )
       if test $? -eq 0
       then
-         newtime[$name]=$( processfeed "$name" "${time[$name]}" "${url[$name]}" )
+         newtime[$name]=$result
       fi
    done
 
