Cleaned up code with suggestions from shellcheck.

diff --git a/rssmail b/rssmail
--- a/rssmail
+++ b/rssmail
@@ -14,17 +14,17 @@ processfeed() {
    tmpfile=$( tempfile )
    maxtime=$lasttime
    WGETFLAGS="$WGETFLAGS -q --timeout=10"
-   wget $WGETFLAGS -O $tmpfile "$url" || { >&2 echo "Error retrieving $url."; rm -f $tmpfile; return 1; }
+   wget $WGETFLAGS -O "$tmpfile" "$url" || { >&2 echo "Error retrieving $url."; rm -f "$tmpfile"; return 1; }
    # First try standard parse
-   $XML sel -t -m "//item" --var linebreak -n --break -o "titl:" -v "title" -n -o "link:" -v "link" -n -o "date:" -v "pubDate" -n -o "desc:" -v "translate(description, \$linebreak, '^')" -n $tmpfile 2> /dev/null > $tmpfile.parsed
+   $XML sel -t -m "//item" --var linebreak -n --break -o "titl:" -v "title" -n -o "link:" -v "link" -n -o "date:" -v "pubDate" -n -o "desc:" -v "translate(description, \$linebreak, '^')" -n "$tmpfile" 2> /dev/null > "$tmpfile.parsed"
    # Next try parse with different XML name spaces
    if test $? -ne 0
    then
-      $XML sel -N purl="http://purl.org/rss/1.0/" -N dc="http://purl.org/dc/elements/1.1/" -t -m "//rdf:RDF/purl:item" --var linebreak -n --break -o "titl:" -v purl:title -n -o "link:" -v purl:link -n -o "date:" -v dc:date -n -o "desc:" -v "translate(purl:description, \$linebreak, '^')" -n $tmpfile 2> /dev/null > $tmpfile.parsed
-      test $? -ne 0 && { >&2 echo "Error parsing feed from $url."; rm -f $tmpfile $tmpfile.parsed; return 1; }
+      $XML sel -N purl="http://purl.org/rss/1.0/" -N dc="http://purl.org/dc/elements/1.1/" -t -m "//rdf:RDF/purl:item" --var linebreak -n --break -o "titl:" -v purl:title -n -o "link:" -v purl:link -n -o "date:" -v dc:date -n -o "desc:" -v "translate(purl:description, \$linebreak, '^')" -n "$tmpfile" 2> /dev/null > "$tmpfile.parsed"
+      test $? -ne 0 && { >&2 echo "Error parsing feed from $url."; rm -f "$tmpfile" "$tmpfile.parsed"; return 1; }
    fi
-   rm -f $tmpfile
-   while read line
+   rm -f "$tmpfile"
+   while read -r line
    do
       fn=${line/:*/}
       data=${line/????:/}
@@ -37,23 +37,23 @@ processfeed() {
          ;;
          "desc")
             desc="$data"
-            if test $lasttime -lt $time
+            if test "$lasttime" -lt "$time"
             then
-               echo -e "<html><body><b>$title</b><p>${desc//^/\\n}<p><a href=$link>$link</a><p><i>Update: $(date -d @$time "+%Y/%m/%d %H:%M:%S")</i></body></html>" | mail -a 'Content-Type: text/html; charset="ISO-8859-1"' -r $mailfrom -s "$name: $title" $mailto
-               test $time -gt $maxtime && maxtime=$time
+               echo -e "<html><body><b>$title</b><p>${desc//^/\\n}<p><a href=$link>$link</a><p><i>Update: $(date -d @"$time" "+%Y/%m/%d %H:%M:%S")</i></body></html>" | mail -a 'Content-Type: text/html; charset="ISO-8859-1"' -r "$mailfrom" -s "$name: $title" "$mailto"
+               test "$time" -gt "$maxtime" && maxtime=$time
             fi
          ;;
       esac
-   done < $tmpfile.parsed
-   rm -f $tmpfile.parsed
-   echo $maxtime
+   done < "$tmpfile.parsed"
+   rm -f "$tmpfile.parsed"
+   echo "$maxtime"
 }
 
 readconfig() {
    cfg=""
    for file in $CONFIG
    do
-      test -f $file && { cfg=$file; break; }
+      test -f "$file" && { cfg=$file; break; }
    done
    test "$cfg" = "" && { echo "No valid config file found ($CONFIG)."; exit 1; }
 
@@ -61,7 +61,7 @@ readconfig() {
    XML=xmlstarlet
 
    items=0
-   while read line
+   while read -r line
    do
       if test "$line" != "" -a "${line:0:1}" != "#"
       then
@@ -69,7 +69,7 @@ readconfig() {
          data=$( echo "$line" | sed 's/[^=]*=\(.*\)/\1/')
          case "$id" in
          "feed")
-            items=$(( $items + 1 ))
+            items=$(( items + 1 ))
             name=$( echo "$data" | sed 's/\([^:]*\):.*/\1/' )
             test "$name" = "" && { echo "Feed has no name."; exit 1; }
             test "$name" != "${name// /}" && { echo "Feed name $name contains spaces."; exit 1; }
@@ -104,14 +104,14 @@ readconfig() {
          ;;
          esac
       fi
-   done < $cfg
+   done < "$cfg"
    test $items -eq 0 && { echo "No feeds found to process."; exit 1; }
    test "$mailto" = "" && { echo "No email-to defined."; exit 1; }
    test "$mailfrom" = "" && { echo "No email-from defined."; exit 1; }
 }
 
 rewriteconfig() {
-   while read line
+   while read -r line
    do
       if test "$line" != "" -a "${line:0:1}" != "#"
       then
@@ -135,8 +135,8 @@ rewriteconfig() {
       else
          echo "$line"
       fi
-   done < $cfg > $cfg.new
-   mv $cfg.new $cfg
+   done < "$cfg" > "$cfg.new"
+   mv "$cfg.new" "$cfg"
 }
 
 sanitycheck() {
@@ -185,7 +185,7 @@ main() {
    readconfig
    sanitycheck
 
-   for name in ${!time[@]}
+   for name in "${!time[@]}"
    do
       result=$( processfeed "$name" "${time[$name]}" "${url[$name]}" )
       if test $? -eq 0
