Fixes by Stephan

diff --git a/rssmail b/rssmail
--- a/rssmail
+++ b/rssmail
@@ -39,7 +39,8 @@ processfeed() {
    rm -f "$tmpfile"
    error=0
    skip=0
-   while read -r line; do
+   while read -r line
+   do
       fn="${line/:*/}"
       data="${line/????:/}"
       case "$fn" in
@@ -73,17 +74,21 @@ processfeed() {
                then
                   err=$(( err + 1 ))
                else
-                  if test "$domail" -eq "1"; then
-                     res=$(echo -e "<html><body><b>$title</b><p>${desc//^/\\n}<p><a href=$link>$link</a><p><i>Update: $(date -d @"$time" "+%Y/%m/%d %H:%M:%S")</i></body></html>" | mail -a 'Content-Type: text/html; charset="ISO-8859-1"' -r "$name <${emailfrom[main]}>" -s "$name: $title" "${emailto[main]}" 2>&1)
-                     test ${PIPESTATUS[0]} -ne 0 && { >&2 echo "Feed ($name): Error sending mail ($res)."; error=1; }
-                     new=$((new + 1))
-                     debug 2 "Sent email for new item: $title"
-                  fi
-                  if test "$dokanboard" -eq "1"; then
-                     res=$(echo '{ "jsonrpc": "2.0", "method": "createTask", "id": 2134420212, "params": { "title": "'$name: $title'", "project_id": '$kbprid', "description": "#Description\n\n'"$desc"'\n\n#Link\n\n'"$link"'" } }' | kanboard | jq -r '.error')
-                     test "$res" != "null" && { >&2 echo "Feed ($name): Error adding task to kanboard (error: $res)."; err=$(($err + 1));}
-                     test "$res" = "null" && new=$(($new + 1))
-                     debug 2 "Adding kanboard entry for new item: $title"
+                  if test ${DEBUG:-0} -lt 4; then
+                      if test "$domail" -eq "1"; then
+                         res=$(echo -e "<html><body><b>$title</b><p>${desc//^/\\n}<p><a href=$link>$link</a><p><i>Update: $(date -d @"$time" "+%Y/%m/%d %H:%M:%S")</i></body></html>" | mail -a 'Content-Type: text/html; charset="UTF-8"' -r "${emailfrom[main]}" -s "$name: $title" "${emailto[main]}" 2>&1)
+                         test ${PIPESTATUS[0]} -ne 0 && { >&2 echo "Feed ($name): Error sending mail ($res)."; error=1; }
+                         new=$((new + 1))
+                         debug 2 "Sent email for new item: $title"
+                      fi
+                      if test "$dokanboard" -eq "1"; then
+                         res=$(echo '{ "jsonrpc": "2.0", "method": "createTask", "id": 2134420212, "params": { "title": "'$name: $title'", "project_id": '$kbprid', "description": "#Description\n\n'"$desc"'\n\n#Link\n\n'"$link"'" } }' | kanboard | jq -r '.error')
+                         test "$res" != "null" && { >&2 echo "Feed ($name): Error adding task to kanboard (error: $res)."; err=$(($err + 1));}
+                         test "$res" = "null" && new=$(($new + 1))
+                         debug 2 "Adding kanboard entry for new item: $title"
+                      fi
+                  else
+                      debug 4 "Sent new item: $title"
                   fi
                fi
                test $time -gt $maxtime && maxtime=$time
@@ -110,16 +115,15 @@ readconfig() {
    # set defaults
    declare -g -A "xml[main]=xmlstarlet"
 
-   while IFS='= ' read var val; do
+   while IFS='= ' read var val
+   do
       if test "${var:0:1}" != "#"; then
-         if [[ $var == \[*] ]]; then
+         if [[ $var == \[*] ]]
+         then
              section="${var:1:-1}"
              debug 4 "Found section: $section"
-             declare -g -A "titleinclude[$section]"
-             declare -g -A "titleexclude[$section]"
-             declare -g -A "linkinclude[$section]"
-             declare -g -A "linkexclude[$section]"
-         elif [[ $val ]]; then
+         elif [[ $val ]]
+         then
              declare -g -A "$var[$section]=$val"
              debug 4 "In section $section, found variable var ($var) with value: $val"
          fi
@@ -134,11 +138,14 @@ readconfig() {
 
 rewriteconfig() {
    debug 4 "Rewriting configuration file to temporary file"
-   while read -r line; do
-      IFS='= ' read var val < <(echo $line)
-      if [[ $line == \[*] ]]; then
-          section=${line:1:-1}
+   while read -r line
+   do
+      IFS='= ' read var val <<< "$line"
+      if [[ $var == \[*] ]]; then
+          section=${var:1:-1}
+          debug 4 "New section [$section]"
       fi
+      debug 5 "var: '$var'='${val:0:30}'"
       if test "$val" -a "$var" = "timestamp" -a "${newtime[$section]}" != ""; then
          stamp=$( date -d "@${newtime[$section]}" "+%Y%m%d %H:%M:%S" )
          if test "$stamp" != "$val"; then
@@ -232,8 +239,8 @@ main() {
 
    itemsok=0
    itemserr=0
-   declare -g -A newtime
-   for name in ${!timestamp[@]}; do
+   for name in ${!timestamp[@]}
+   do
       debug 1 "Starting feed $name"
       if test "${timestamp[$name]}" = ""; then
          timestamp[$name]=$( date "+%s" )
@@ -244,11 +251,12 @@ main() {
       if test "$maxtime" != ""; then
          itemsok=$(( $itemsok + $new ))
          itemserr=$(( $itemserr + $err ))
-         newtime[$name]=$maxtime
+         declare -g -A newtime[$name]=$maxtime
       fi
    done
    debug 1 "Feed processing done."
    test $(( $itemsok + $itemserr )) -gt 0 -a $dokanmail -eq 1 && { ( test $itemsok -gt 0 && echo -e "There are $itemsok items added to kanboard ${kanboardproject[main]}."; test $itemserr -gt 0 && echo -e "There are $itemserr items that failed to parse." ) | mail -r "${emailfrom[main]}" -s "rssmail: $itemsok items added to kanboard" "${emailto[main]}"; }
+
    rewriteconfig
 }
 
